[workspace]
members = ["axum-s3"]

[package]
name = "tortoaster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "0.12.1", features = ["markdown"] }
aws-config = "1.2.0"
aws-sdk-s3 = "1.23.0"
axum = { version = "0.7.4", features = ["macros", "multipart"] }
axum-extra = { version = "0.9.2", features = ["typed-routing"] }
axum-s3 = { path = "axum-s3" }
axum-valid = "0.17.0"
backoff = { version = "0.4.0", features = ["tokio"] }
sea-orm = { version = "0.12.15", default-features = false, features = ["macros", "runtime-tokio-rustls", "sqlx-postgres", "with-time", "with-uuid"] }
serde = { version = "1.0.196", features = ["derive"] }
sqlx = { version = "0.7.3", features = ["runtime-tokio-rustls", "postgres", "time"] }
thiserror = "1.0.56"
time = { version = "=0.3.34", features = ["serde"] }
time-humanize = "0.1.3"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
toml = "0.8.10"
tower-http = { version = "0.5.1", features = ["fs"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = { version = "1.8.0", features = ["fast-rng", "serde", "v4"] }
validator = { version = "0.17.0", features = ["derive"] }
