services:
  backend:
    profiles: [ "full" ]
    build:
      dockerfile: "Dockerfile"
    pull_policy: build
    ports: [ "8000:8000" ]
    environment:
      HOST: "0.0.0.0"
      RUST_LOG: "toast=info,warn"
      DATABASE__URL: "sqlite://sqlite.db"
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      object-store-migrate:
        condition: service_completed_successfully

  db-migrate:
    build:
      dockerfile: "sqlx.Dockerfile"
    working_dir: "/app"
    command: [ "migrate", "run", "--source", "migrations", "--source", "fixtures" ]
    volumes:
      - "./migrations:/app/migrations:ro"
      - "./fixtures:/app/fixtures:ro"
      - "./sqlite.db:/app/sqlite.db:rw"
    environment:
      DATABASE_URL: "sqlite://sqlite.db"

  object-store:
    image: quay.io/minio/minio
    command: "server /data --address 0.0.0.0:9000 --console-address 0.0.0.0:8001"
    ports:
      - "9000:9000"
      - "8001:8001"
    environment:
      MINIO_HOST: "0.0.0.0"
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_IDENTITY_OPENID_CONFIG_URL: "http://iam-provider:8003/realms/master/.well-known/openid-configuration"
      MINIO_IDENTITY_OPENID_CLIENT_ID: "minio"
      MINIO_IDENTITY_OPENID_CLIENT_SECRET: "pNvFwKbjguoTGCibt9ErDdgwHYif1pN4"
      MINIO_IDENTITY_OPENID_DISPLAY_NAME: "KeyCloak Admin"
      MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC: "on"
    healthcheck:
      test: "curl -I http://localhost:9000/minio/health/live"
      interval: 1s
      retries: 10

  object-store-migrate:
    image: quay.io/minio/mc
    volumes: [ "./bucket_data:/app:ro" ]
    depends_on:
      object-store:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c " \
        /usr/bin/mc alias set myminio http://object-store:9000 user password && \
        /usr/bin/mc mb --ignore-existing --region "eu-central-1" --with-versioning myminio/toast && \
        /usr/bin/mc anonymous set download myminio/toast && \
        /usr/bin/mc mirror --overwrite /app myminio/toast \
      "
