version: '3.9'
services:
  tortoaster:
    image: dev
    build:
      dockerfile: "dev.Dockerfile"
    volumes: [ ".:/app" ]
    working_dir: "/app"
    ports: [ "8000:8000" ]
    environment:
      HOST: "0.0.0.0"
      DATABASE_URL: "postgres://tortoaster:password@postgres/tortoaster"

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: "tortoaster"
      POSTGRES_PASSWORD: "password"
    ports: [ "5432:5432" ]
