# host = "127.0.0.1" # default: 127.0.0.1
# port = 8000 # default: 8000
rust_log = "tortoaster=trace,warn" # default: info

[database]
url = "postgres://tortoaster@localhost/tortoaster"
password = "password"

[s3]
region = "eu-central-1"
endpoint_url = "http://localhost:9000"
access_key_id = "tortoaster"
secret_access_key = "password"
# session_token = "" # default: None
thumbnail_bucket_url = "http://localhost:9000/tortoaster-thumbnails"

# [s3.bucket]
# thumbnails = "tortoaster-thumbnails" # default: tortoaster-thumbnails
# content = "tortoaster-content" # default: tortoaster-content
# system = "tortoaster-system" # default: tortoaster-system

[oidc]
client_id = "tortoaster"
client_secret = "UzuoAuMFtHuf4USSl2CVGmgXockttxxh" # default: None
issuer_url = "http://localhost:8003/realms/tortoaster"
redirect_url = "http://localhost:8000/projects"

# [cache]
# host = "localhost" # default: localhost
# port = 6379 # default: 6379
