# host = "127.0.0.1" # default: 127.0.0.1
# port = 8000 # default: 8000
rust_log = "toast=trace,warn" # default: info

[database]
url = "postgres://user@localhost/toast"
password = "password"

[s3]
region = "eu-central-1"
endpoint_url = "http://localhost:9000"
access_key_id = "user"
secret_access_key = "password"
# session_token = "" # default: None
# bucket_name = "toast" # default: toast

[oidc]
client_id = "tortoaster"
client_secret = "UzuoAuMFtHuf4USSl2CVGmgXockttxxh" # default: None
issuer_url = "http://localhost:8003/realms/tortoaster"
redirect_url = "http://localhost:8000/projects"
